import time

input("Enter Hwid: ") 
time.sleep(3) 
print(" W e l c o m e ") 
time.sleep(3) 
print("╦╔═╗┌─┐┬ ┬┌─┐┌┐┌┌─┐┌─┐") 
print("║╠═╝│  ├─┤├─┤││││ ┬├┤ ") 
print("╩╩  └─┘┴ ┴┴ ┴┘└┘└─┘└─┘") 
time.sleep(4) 
print("╔═╗┬─┐┬┬  ┬┌─┐┌┬┐┌─┐") 
print("╠═╝├┬┘│└┐┌┘├─┤ │ ├┤ ") 
print("╩  ┴└─┴ └┘ ┴  ┴ ┴ └─┘") 
time.sleep(4) 
print("╔╗ ┬ ┬") 
print("╠╩╗└┬┘") 
print("╚═╝ ┴ ") 
time.sleep(4) 
print("┌─┐─┐ ┬┌─┐┌─┐┌┬┐┌─┐┬─┐┬─┐") 
time.sleep(3) 
print("┌─┘┌┴┬┘│  │ │ ││├┤ ├┬┘├┬┘") 
time.sleep(3) 
print("└─┘┴ └─└─┘└─┘─┴┘└─┘┴└─┴└─") 
input(" Enter new IP: ") 
input(" Enter new port: ") 
input(" Enter new DNS: ") 
print(" changing.... ") 
time.sleep(7) 
print(" Succes! ") 
input() 
